apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache
    env: prod
    tier: frontend
    owner: simbu
spec:
  containers:
    - name: apache-container
      image: httpd:2.4
      ports:
       -  name: http
          containerPort: 80