apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
        env: prod
        tier: frontend
        owner: simbu
    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
          - name: mysql
            containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
  replicas: 3
  selector:
    matchLabels:
      app: mysql
      env: prod
      tier: frontend
      owner: simbu


