apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp-pod
spec:
  selector:
    app: webapp-podv1
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010