apiVersion: v1
kind: ReplicationController
metadata:
  name: apache-rs
  labels:
    app: apache
    env: prod
    tier: frontend
spec:
  template:
    metadata:
      name: apache-pod
      labels:
        app: httpd
        env: prod
    spec:
      containers:
        - name: apache-container
          image: httpd:2.4
          ports:
           - containerPort: 80
  replicas: 2