apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: httpd
    env: prod
spec:
  containers:
    - name: apache-container
      image: httpd:2.4
      ports:
       - containerPort: 80    