apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apache-rs
  labels:
    app: apache
spec:
  template:
    metadata:
      name: apache-pod
      labels:
        app: apache
        env: prod
        tier: frontend
        owner: simbu
    spec:
      containers:
        - name: apache-container
          image: httpd:2.4
          ports:
          - name: http
            containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: apache
      env: prod
      tier: frontend
      owner: simbu

    