apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  selector:
    app: apache
    env: prod
    tier: frontend
    owner: simbu
  type: NodePort
  ports:
    - nodePort: 30050
      port: 80
      targetPort: 80
