apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  selector:
    app: mysql
    env: prod
    tier: frontend
    owner: simbu
  type: ClusterIP
  ports:
    - port: 3306
      